#ifndef HARDWAREDEBUG_GLOBAL_H
#define HARDWAREDEBUG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HARDWAREDEBUG_LIBRARY)
#  define HARDWAREDEBUGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HARDWAREDEBUGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HARDWAREDEBUG_GLOBAL_H
